# Generated by Django 4.1.7 on 2023-03-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_group_remove_student_group_student_favoritenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='favoriteNumber',
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.IntegerField(default=921),
        ),
    ]
