# Generated by Django 4.1.7 on 2023-03-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_remove_student_favoritenumber_student_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.AddField(
            model_name='student',
            name='favoriteNumber',
            field=models.IntegerField(default=0),
        ),
    ]
