# Generated by Django 4.1.7 on 2023-03-10 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_remove_student_group_student_favoritenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='favoriteNumber',
            new_name='group',
        ),
    ]
