# Generated by Django 4.1.7 on 2023-03-10 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_rename_favoritenumber_student_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='group',
            new_name='favoriteNumber',
        ),
    ]
