# Generated by Django 4.1.7 on 2023-03-10 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_rename_group_student_favoritenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('TeachingSubject', models.CharField(max_length=200)),
                ('years_of_experience', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='StudentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.student'),
        ),
        migrations.AddField(
            model_name='group',
            name='groupNickname',
            field=models.CharField(default='unknown name', max_length=200),
        ),
        migrations.AddField(
            model_name='group',
            name='language',
            field=models.CharField(default='romana', max_length=200),
        ),
    ]
