# Generated by Django 4.1.7 on 2023-03-10 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_teacher_group_studentid_group_groupnickname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='StudentId',
        ),
        migrations.AddField(
            model_name='group',
            name='year',
            field=models.IntegerField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='GroupId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.group'),
        ),
    ]
